# Generated by Django 5.0.2 on 2024-06-01 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpurchase',
            name='cname',
        ),
    ]
