# Generated by Django 5.0.2 on 2024-06-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_trip_orderno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpurchase',
            old_name='orderno',
            new_name='order',
        ),
        migrations.AddField(
            model_name='cpurchase',
            name='vendor',
            field=models.TextField(null=True),
        ),
    ]
