# Generated by Django 5.0.2 on 2024-06-01 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_orderno_cpurchase_order_cpurchase_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderno',
            old_name='tripnumber',
            new_name='ordernumber',
        ),
    ]
