# Generated by Django 5.0.2 on 2024-06-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_cpurchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpurchase',
            name='Sfilters',
            field=models.TextField(null=True),
        ),
    ]
